package com.example.internetaccess.core.di.network_module

import com.example.internetaccess.BuildConfig
import com.example.internetaccess.core.utils.LiveOkhttpLoggingInterceptor
import com.example.internetaccess.services.InternetServices
import com.google.gson.Gson
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Converter
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import timber.log.Timber
import java.util.concurrent.TimeUnit
import javax.inject.Named
import javax.inject.Singleton

const val BASE_URL = "http://ec2-157-175-229-147.me-south-1.compute.amazonaws.com:8080/"
const val TOKEN =
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2NjI0NzE4OTksInVzZXJDcmVkZW50aWFsSWQiOjEsInJvbGVzIjpbIlVTRVJfTElTVCIsIlVTRVJfVklFVyIsIlVTRVJfVVBEQVRFIiwiVVNFUl9ERUxFVEUiLCJVU0VSX0NSRUFURSIsIk1FUkNIQU5UX0xJU1QiLCJNRVJDSEFOVF9WSUVXIiwiTUVSQ0hBTlRfVVBEQVRFIiwiTUVSQ0hBTlRfREVMRVRFIiwiTUVSQ0hBTlRfQ1JFQVRFIiwiU0lURV9MSVNUIiwiU0lURV9WSUVXIiwiU0lURV9VUERBVEUiLCJTSVRFX0RFTEVURSIsIlNJVEVfQ1JFQVRFIiwiQ09VTlRSWV9MSVNUIiwiQ09VTlRSWV9WSUVXIiwiQ09VTlRSWV9VUERBVEUiLCJDT1VOVFJZX0RFTEVURSIsIkNPVU5UUllfQ1JFQVRFIiwiQ0lUWV9MSVNUIiwiQ0lUWV9WSUVXIiwiQ0lUWV9VUERBVEUiLCJDSVRZX0RFTEVURSIsIkNJVFlfQ1JFQVRFIiwiWk9ORV9MSVNUIiwiWk9ORV9WSUVXIiwiWk9ORV9VUERBVEUiLCJaT05FX0RFTEVURSIsIlpPTkVfQ1JFQVRFIiwiQkFOS19MSVNUIiwiQkFOS19WSUVXIiwiQkFOS19VUERBVEUiLCJCQU5LX0RFTEVURSIsIkJBTktfQ1JFQVRFIiwiTkZDX0xJU1QiLCJORkNfVklFVyIsIk5GQ19VUERBVEUiLCJORkNfREVMRVRFIiwiTkZDX0NSRUFURSIsIk1BU1RFUl9DT1JQT1JBVEVfTElTVCIsIk1BU1RFUl9DT1JQT1JBVEVfVklFVyIsIk1BU1RFUl9DT1JQT1JBVEVfVVBEQVRFIiwiTUFTVEVSX0NPUlBPUkFURV9ERUxFVEUiLCJNQVNURVJfQ09SUE9SQVRFX0NSRUFURSIsIkNPUlBPUkFURV9MSVNUIiwiQ09SUE9SQVRFX1ZJRVciLCJDT1JQT1JBVEVfVVBEQVRFIiwiQ09SUE9SQVRFX0RFTEVURSIsIkNPUlBPUkFURV9DUkVBVEUiLCJDT1JQT1JBVEVfQ09OVEFDVF9MSVNUIiwiQ09SUE9SQVRFX0NPTlRBQ1RfVklFVyIsIkNPUlBPUkFURV9DT05UQUNUX1VQREFURSIsIkNPUlBPUkFURV9DT05UQUNUX0RFTEVURSIsIkNPUlBPUkFURV9DT05UQUNUX0NSRUFURSIsIlBST0RVQ1RfQ0FURUdPUllfTElTVCIsIlBST0RVQ1RfQ0FURUdPUllfVklFVyIsIlBST0RVQ1RfQ0FURUdPUllfVVBEQVRFIiwiUFJPRFVDVF9DQVRFR09SWV9ERUxFVEUiLCJQUk9EVUNUX0NBVEVHT1JZX0NSRUFURSIsIlJPTEVfTElTVCIsIlJPTEVfVklFVyIsIlJPTEVfVVBEQVRFIiwiUk9MRV9ERUxFVEUiLCJST0xFX0NSRUFURSIsIk9UVV9MSVNUIiwiT1RVX1ZJRVciLCJPVFVfVVBEQVRFIiwiT1RVX0RFTEVURSIsIk9UVV9DUkVBVEUiLCJUUkFOU0FDVElPTl9MSVNUIiwiVFJBTlNBQ1RJT05fVklFVyIsIlRSQU5TQUNUSU9OX1VQREFURSIsIlRSQU5TQUNUSU9OX0RFTEVURSIsIlRSQU5TQUNUSU9OX0NSRUFURSIsIk1BU1RFUl9NRVJDSEFOVF9MSVNUIiwiTUFTVEVSX01FUkNIQU5UX1ZJRVciLCJNQVNURVJfTUVSQ0hBTlRfVVBEQVRFIiwiTUFTVEVSX01FUkNIQU5UX0RFTEVURSIsIk1BU1RFUl9NRVJDSEFOVF9DUkVBVEUiLCJBU1NFVF9MSVNUIiwiQVNTRVRfVklFVyIsIkFTU0VUX1VQREFURSIsIkFTU0VUX0RFTEVURSIsIkFTU0VUX0NSRUFURSIsIkNPUlBPUkFURV9CSUxMSU5HX0FDQ09VTlRfTElTVCIsIkNPUlBPUkFURV9CSUxMSU5HX0FDQ09VTlRfVklFVyIsIkNPUlBPUkFURV9CSUxMSU5HX0FDQ09VTlRfVVBEQVRFIiwiQ09SUE9SQVRFX0JJTExJTkdfQUNDT1VOVF9ERUxFVEUiLCJDT1JQT1JBVEVfQklMTElOR19BQ0NPVU5UX0NSRUFURSIsIlBST0RVQ1RfQlVMS19DUkVBVEUiLCJQUk9EVUNUX0xJU1QiLCJQUk9EVUNUX1ZJRVciLCJQUk9EVUNUX1VQREFURSIsIlBST0RVQ1RfREVMRVRFIiwiUFJPRFVDVF9DUkVBVEUiLCJQT0xJQ1lfTElTVCIsIlBPTElDWV9WSUVXIiwiUE9MSUNZX1VQREFURSIsIlBPTElDWV9ERUxFVEUiLCJQT0xJQ1lfQ1JFQVRFIiwiU0hJRlRfTElTVCIsIlNISUZUX1ZJRVciLCJTSElGVF9VUERBVEUiLCJTSElGVF9ERUxFVEUiLCJTSElGVF9DUkVBVEUiLCJNRVJDSEFOVF9DT05UQUNUX0xJU1QiLCJNRVJDSEFOVF9DT05UQUNUX1ZJRVciLCJNRVJDSEFOVF9DT05UQUNUX1VQREFURSIsIk1FUkNIQU5UX0NPTlRBQ1RfREVMRVRFIiwiTUVSQ0hBTlRfQ09OVEFDVF9DUkVBVEUiLCJNRVJDSEFOVF9CQU5LX0FDQ09VTlRfTElTVCIsIk1FUkNIQU5UX0JBTktfQUNDT1VOVF9WSUVXIiwiTUVSQ0hBTlRfQkFOS19BQ0NPVU5UX1VQREFURSIsIk1FUkNIQU5UX0JBTktfQUNDT1VOVF9ERUxFVEUiLCJNRVJDSEFOVF9CQU5LX0FDQ09VTlRfQ1JFQVRFIiwiSU5WT0lDRV9TRVRUTEUiLCJJTlZPSUNFX0xJU1QiLCJJTlZPSUNFX1ZJRVciLCJJTlZPSUNFX1VQREFURSIsIklOVk9JQ0VfQ1JFQVRFIiwiSU5WT0lDRV9ERUxFVEUiLCJBU1NFVF9UQUdfTElTVCIsIkFTU0VUX1RBR19WSUVXIiwiQVNTRVRfVEFHX1VQREFURSIsIkFTU0VUX1RBR19ERUxFVEUiLCJBU1NFVF9UQUdfQ1JFQVRFIiwiREFTSEJPQVJEX0xJU1QiLCJEQVNIQk9BUkRfVklFVyIsIlNBTEVTX0xJU1QiLCJTQUxFU19WSUVXIiwiSU5WT0lDRV9QQUNLQUdFX0xJU1QiLCJJTlZPSUNFX1BBQ0tBR0VfVklFVyIsIklOVk9JQ0VfUEFDS0FHRV9VUERBVEUiLCJJTlZPSUNFX1BBQ0tBR0VfQ1JFQVRFIiwiTUVSQ0hBTlRfRE9DVU1FTlRfTElTVCIsIk1FUkNIQU5UX0RPQ1VNRU5UX1ZJRVciLCJNRVJDSEFOVF9ET0NVTUVOVF9VUERBVEUiLCJNRVJDSEFOVF9ET0NVTUVOVF9ERUxFVEUiLCJNRVJDSEFOVF9ET0NVTUVOVF9DUkVBVEUiLCJNSUxFQUdFX0lNQUdFX0xJU1QiLCJNSUxFQUdFX0lNQUdFX1ZJRVciLCJBTEVSVF9MSVNUIiwiQUxFUlRfVklFVyIsIkNPUlBPUkFURV9ET0NVTUVOVF9MSVNUIiwiQ09SUE9SQVRFX0RPQ1VNRU5UX1ZJRVciLCJDT1JQT1JBVEVfRE9DVU1FTlRfVVBEQVRFIiwiQ09SUE9SQVRFX0RPQ1VNRU5UX0RFTEVURSIsIkNPUlBPUkFURV9ET0NVTUVOVF9DUkVBVEUiLCJTU1NfVVNFUl9MSVNUIiwiU1NTX1VTRVJfVklFVyIsIlNTU19VU0VSX1VQREFURSIsIlNTU19VU0VSX0RFTEVURSIsIlNTU19VU0VSX0NSRUFURSIsIk1FUkNIQU5UX1VTRVJfTElTVCIsIk1FUkNIQU5UX1VTRVJfVklFVyIsIk1FUkNIQU5UX1VTRVJfVVBEQVRFIiwiTUVSQ0hBTlRfVVNFUl9ERUxFVEUiLCJNRVJDSEFOVF9VU0VSX0NSRUFURSIsIkNPUlBPUkFURV9VU0VSX0xJU1QiLCJDT1JQT1JBVEVfVVNFUl9WSUVXIiwiQ09SUE9SQVRFX1VTRVJfVVBEQVRFIiwiQ09SUE9SQVRFX1VTRVJfREVMRVRFIiwiQ09SUE9SQVRFX1VTRVJfQ1JFQVRFIiwiTUVSQ0hBTlRfQklMTElOR19BQ0NPVU5UX1ZJRVciLCJNRVJDSEFOVF9CSUxMSU5HX0FDQ09VTlRfVVBEQVRFIiwiTUVSQ0hBTlRfQklMTElOR19BQ0NPVU5UX0RFTEVURSIsIk1FUkNIQU5UX0JJTExJTkdfQUNDT1VOVF9DUkVBVEUiLCJNRVJDSEFOVF9EZXBvc2l0X0xJU1QiLCJDTElFTlRfQ1JFREVOVElBTF9DUkVBVEUiXSwiaXNzIjoiU1NTIiwidXNlclR5cGUiOiJBRE1JTklTVFJBVElPTiIsImV4cCI6MTY2MjU1ODI5OSwiaWF0IjoxNjYyNDcxODk5LCJ1c2VySWQiOjEsImp0aSI6IjU0MWM1ZTljLTM0ODctNGQ1Ny1hNGZmLTFhYTYyZWUzYzZhZCJ9.qlZYFEzSfFOPApB_5W2agoUiThMHZ-fUFWYHdQUl-QIOkuy4-jbae3aJw6E5tOX1_B5lrnb49O6g86VXISiaQgQTYNeDZGJNgb1oYYFEpQ7DAD7Du9dtrK7lCWrZj0YcwCOUnR9knCNJsIdhjIEoa3jbVmd55bR8cCBc9tdg2r3FJKavDsE08Y0JqijzdrOp8BqJIih-0CIAAaV1_Q0lM7cMFzaC-ABbZFVhiklrTnDFZdLfDZVdknSHMnz8YHf8uH9IbBiR7SpN_zNMbW9RU2mJLOpf1RfdyB0VjvMbDYdhwAwDT_Y6PhQyDnapBmEX5iGEbCEWlCOQTLt5qCH5ug"

@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    @Singleton
    @Provides
    fun provideInternetService(retrofit: Retrofit): InternetServices =
        retrofit.create(InternetServices::class.java)

    @Singleton
    @Provides
    fun provideGson() = Gson()

    @Provides
    fun provideConverterFactory(gson: Gson): Converter.Factory {
        return GsonConverterFactory.create(gson)
    }

    @Provides
    @Named("AuthInterceptor")
    fun provideAuthInterceptor(): Interceptor = Interceptor { chain ->
        val newBuilder = chain.request()
            .newBuilder()
        newBuilder.addHeader("Authorization", "Bearer $TOKEN")
        newBuilder.build().let { chain.proceed(it) }
    }


    @Provides
    @Named("LoggingInterceptor")
    @Singleton
    fun httpLoggingInterceptor(): Interceptor {
        return if (BuildConfig.DEBUG)
            HttpLoggingInterceptor { message ->
                Timber.tag("OkHttp").d(message)
            }.setLevel(HttpLoggingInterceptor.Level.BODY)
        else
            return LiveOkhttpLoggingInterceptor { message ->
                Timber.tag("OKHttp").d(message)

            }.setLevel(HttpLoggingInterceptor.Level.BODY)
    }


    @Singleton
    @Provides
    fun client(
        @Named("AuthInterceptor")
        authInterceptor: Interceptor,
        @Named("LoggingInterceptor")
        loggingInterceptor: Interceptor,
    ): OkHttpClient =
        OkHttpClient().newBuilder().run {
            addInterceptor(authInterceptor)
            addInterceptor(loggingInterceptor)
            connectTimeout(2, TimeUnit.MINUTES)
            readTimeout(2, TimeUnit.MINUTES)
            build()
        }

    @Singleton
    @Provides
    fun provideRetrofit(
        okHttpClient: OkHttpClient,
        converterFactory: Converter.Factory,
    ): Retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .addConverterFactory(converterFactory)
        .client(okHttpClient)
        .build()
}


